---
version: '3.3'  # 3.3 needed for build/contexts, 'targets' not included
services:
  blackmirror:
    build: .
    environment:
      - APP_SETTINGS=development
      - PGHOST=db
      - PGPORT=5432
      - PGUSER=postgres
      - PGDATABASE=blackmirror
      - DATABASE_URL=postgres://db:5432/blackmirror?sslmode=disable
      - SSLMODE=prefer
    depends_on:
      - db
    volumes:
      - ./:/app

  db:
    image: postgres:11.5
    restart: unless-stopped
    command: postgres -c max_connections=500
    environment:
      - PGUSER=postgres
    ports:
      - 5432:5432

  # redis:
  #   command: redis-server --dbfilename 'redis.rdb'
  #   restart: unless-stopped
  #   image: redis:3-alpine
  #   ports:
  #     - 6379:6379
  #   volumes:
  #     - ./redis/:/data
