---
version: '3.3'  # 3.3 needed for build/contexts, 'targets' not included
services:
  blackmirror:
    build: .
    environment:
      - APP_SETTINGS=development
      - PGHOST=pg-35c52044-villej-eec9.aivencloud.com
      - PGPORT=12819
      - PGUSER=avnadmin
      - PGDATABASE=defaultdb
      - SSLMODE=require
      - REDISHOST=redis-16c88dcf-villej-eec9.aivencloud.com
      - REDISPORT=12820
    depends_on:
      - db
      - redis
      - bmqueue
    volumes:
      - ./:/app
  bmqueue:
    build: .
    command:
      - bash
      - bin/run_queue
    volumes:
      - ./:/app
    environment:
      - APP_SETTINGS=development
      - PGHOST=pg-35c52044-villej-eec9.aivencloud.com
      - PGPORT=12819
      - PGUSER=avnadmin
      - PGDATABASE=defaultdb
      - SSLMODE=require
      - REDISHOST=redis-16c88dcf-villej-eec9.aivencloud.com
      - REDISPORT=12820
    depends_on:
      - redis
      - db
    volumes:
      - ./:/app
  db:
    image: postgres:11.5
    restart: unless-stopped
    command: postgres -c max_connections=500
    environment:
      - PGUSER=postgres
    ports:
      - 5432:5432
  redis:
    command: redis-server --dbfilename 'redis.rdb'
    restart: unless-stopped
    image: redis:3-alpine
    ports:
      - 6379:6379
    volumes:
      - ./redis/:/data
